config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'
   get 'about' => 'welcome#about'
   resources :articles
   get 'signup' => 'users#new'
   post 'users' => 'users#create'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: {maximum: 50,minimum: 3}
  validates :description, presence: true, length: {minimum: 3, maximum: 350}
  validates :user_id, presence: true  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true,format: {with: VALID_EMAIL_REGEX}
  validates :username, presence: true, length: {minimum: 3, maximum: 25}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def new
    @article=Article.new
  end

  def create
   # debugger
    @article=Article.new(article_params)
    @article.user=User.first
    
    @article.save
    if @article.save
      redirect_to article_path(@article)
      flash[:success]="article was successfully created"
    else
      render 'new'
    end
  end 

  private def article_params
    params.require(:article).permit(:title, :description)
  end

  def show
    @article=Article.find(params[:id])
  end

  def edit
    @article=Article.find(params[:id])
  end

  def update
    @article=Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article)
      flash[:success]="Article is updated successfully"
    else
      render 'edit'
    end
  end

  def index
    @articles=Article.all  
  end
  
  def destroy
    @article=Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
    flash[:danger]="Article is deleted !"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user=User.new
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
 

<div class='row'>
  <div class='col-md-12'>
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"} ) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :title %> 
      </div>
      <div class="col-sm-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Title of the Article", autofocus: true%>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-2">
        <%= f.label :description%>
      </div>
      <div class="col-sm-8">
          <%= f.text_area :description, class: "form-control", rows: 15,placeholder: "Body of the Article",autofocus: true %>
      </div>
    </div>
    <div class="col-sm-offset-2 col-sm-10">
  <%= f.submit  "Create Blog", class: "btn btn-primary btn-lg"%>
  </div>
  </div>
  <%end%>
  <div class="col-xs-4 col-xs-offset-4">
  [<%= link_to "Cancel request", articles_path%>]
  </div>
</div>
</div>

app/views/articles/edit.html.erb
<h1>Editing the dataset</h1>
<%= render 'form' %>
<%= link_to 'Back to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1 align="center">List of all the Articles</h1>
  <% @articles.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%=link_to article.title, article_path(article)%>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <small> Created by: <%=article.user.username if article.user%></small>
        </div>
        <div class="article-actions">
          <%= link_to 'Edit this article', edit_article_path(article) ,class: "btn btn-xs btn-primary"%>
          <%= link_to 'Delete this article', article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article ?"},class: "btn btn-xs btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/articles/new.html.erb
<h1> New Article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"> <%=@article.title%> </h2>
<div class="well col-xs-8 col-xs-offset-2">
    
    <%= simple_format(@article.description) %>
    <div class="article-actions">
        <%= link_to 'Edit this article', edit_article_path(@article) ,class: "btn btn-xs btn-primary"%>
        <%= link_to 'Delete this article', article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article ?"},class: "btn btn-xs btn-danger" %>
        <%= link_to 'Back to My articles', articles_path, class: "btn btn-xs btn-success" %>
        
    </div>
</div>
    

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Blogworks is made with Ruby on Rails and Bootstrap
    </small>
  
  
  </footer>
  
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    
<% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>' >
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <ul>
      <li><%= msg %></li>
    </ul>
<%end%>
</div>
  
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" id="logo" href="#">Blogworks</a>-->
      <%= link_to "Blogworks", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About Us", about_path %></li>
        <li><%=link_to 'Contact Us'%></li>
        <li><%= link_to 'Articles', articles_path%></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%=debug(params) if Rails.env.development?%>
  
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error")%>
      prohibited from saving this page:
        </h2>    
    <div class="panel-body">
    <ul>
    <% obj.errors.full_messages.each do |msg|%>
      <li> <%= msg %></li>
    <%end%>
  </ul>
  </div>
 </div>
  </div>
  </div>
  </div>


<%end%>

 

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= render 'shared/errors', obj: @user %>
 

<div class='row'>
  <div class='col-md-12'>
  <%= form_for(@user, :html => {class: "form-horizontal", role: "form"} ) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :username %> 
      </div>
      <div class="control-label col-sm-3">
        <%= f.text_field :username, class: "form-control", placeholder: "How to call you ?", autofocus: true%>
      </div>
    </div>
    
    
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :fname%>
      </div>
      <div class="control-label col-sm-3">
          <%= f.text_field :password, class: "form-control",placeholder: "First Name",autofocus: true %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :"Last Name"%>
      </div>
      <div class="control-label col-sm-3">
          <%= f.text_field :password, class: "form-control",placeholder: "Last Name",autofocus: true %>
      </div>
    </div>
    
    
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :Password%>
      </div>
      <div class="control-label col-sm-3">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter your password",autofocus: true %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :"Re-Enter Password"%>
      </div>
      <div class="control-label col-sm-3">
          <%= f.password_field :password, class: "form-control",placeholder: "Re-Enter your password",autofocus: true %>
      </div>
    </div>
    
    
    <div class="col-sm-offset-2 col-sm-10">
  <%= f.submit  "Create Account", class: "btn btn-primary btn-lg"%>
  </div>
  </div>
  <%end%>
  <div class="col-xs-4 col-xs-offset-4">
  [<%= link_to "Cancel request", articles_path%>]
  </div>
</div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome to About page</h1>

app/views/welcome/index.html.erb
<div class="jumbotron">
<h1>Welcome to Blogworks</h1>
<%= link_to "Sign Up", signup_path, class:"btn btn-primary btn-lg"%>
</div>
<%= link_to 'About', about_path %>

<%= link_to 'Create New Blog', new_article_path %>